"""
Comprehensive Dataset for Animal Kingdom Knowledge Graph.
Contains 39 diverse animals across Mammals, Birds, Reptiles, Amphibians, Fish, and Insects.
With verified high-definition Unsplash URLs accessible from web browsers without 403 or CORS restrictions.
"""

CLASSES_DATA = [
    {"id": "class_mammal", "name": "Mammal"},
    {"id": "class_bird", "name": "Bird"},
    {"id": "class_reptile", "name": "Reptile"},
    {"id": "class_amphibian", "name": "Amphibian"},
    {"id": "class_fish", "name": "Fish"},
    {"id": "class_insect", "name": "Insect"},
]

DIETS_DATA = [
    {"id": "diet_carnivore", "name": "Carnivore"},
    {"id": "diet_herbivore", "name": "Herbivore"},
    {"id": "diet_omnivore", "name": "Omnivore"},
    {"id": "diet_insectivore", "name": "Insectivore"},
]

CONSERVATION_STATUSES_DATA = [
    {"id": "status_least_concern", "name": "Least Concern"},
    {"id": "status_near_threatened", "name": "Near Threatened"},
    {"id": "status_vulnerable", "name": "Vulnerable"},
    {"id": "status_endangered", "name": "Endangered"},
    {"id": "status_critically_endangered", "name": "Critically Endangered"},
]

CONTINENTS_DATA = [
    {"id": "continent_asia", "name": "Asia"},
    {"id": "continent_africa", "name": "Africa"},
    {"id": "continent_europe", "name": "Europe"},
    {"id": "continent_north_america", "name": "North America"},
    {"id": "continent_south_america", "name": "South America"},
    {"id": "continent_australia", "name": "Australia"},
    {"id": "continent_antarctica", "name": "Antarctica"},
]

HABITATS_DATA = [
    {
        "id": "habitat_forest",
        "name": "Forest",
        "description": "Dense woodland ecosystems rich in biodiversity and canopy cover.",
        "continents": ["Asia", "Europe", "North America", "South America", "Africa"]
    },
    {
        "id": "habitat_grassland",
        "name": "Grassland",
        "description": "Open expansive terrain dominated by grasses, herbs, and few trees.",
        "continents": ["Africa", "Asia", "North America", "South America", "Australia"]
    },
    {
        "id": "habitat_savanna",
        "name": "Savanna",
        "description": "Tropical grassland with scattered trees, distinct wet and dry seasons.",
        "continents": ["Africa", "Australia", "South America"]
    },
    {
        "id": "habitat_desert",
        "name": "Desert",
        "description": "Arid biome with sparse rainfall, extreme temperatures, and specialized wildlife.",
        "continents": ["Africa", "Asia", "Australia", "North America", "South America"]
    },
    {
        "id": "habitat_ocean",
        "name": "Ocean",
        "description": "Vast marine saltwater ecosystems spanning deep waters and coastal reefs.",
        "continents": ["Asia", "Africa", "Europe", "North America", "South America", "Australia", "Antarctica"]
    },
    {
        "id": "habitat_river",
        "name": "River",
        "description": "Freshwater flowing aquatic ecosystems providing essential riparian corridors.",
        "continents": ["Asia", "Africa", "Europe", "North America", "South America", "Australia"]
    },
    {
        "id": "habitat_wetland",
        "name": "Wetland",
        "description": "Marshlands, swamps, and bogs where water covers soil seasonally or permanently.",
        "continents": ["Asia", "Africa", "Europe", "North America", "South America", "Australia"]
    },
    {
        "id": "habitat_mountain",
        "name": "Mountain",
        "description": "High-altitude rugged terrain with steep slopes and alpine vegetation.",
        "continents": ["Asia", "Europe", "North America", "South America", "Africa"]
    },
    {
        "id": "habitat_polar",
        "name": "Polar Tundra",
        "description": "Frigid ice caps and permafrost biomes with sub-zero temperatures.",
        "continents": ["Antarctica", "North America", "Europe", "Asia"]
    }
]

ANIMALS_DATA = [
    {
        "id": "animal_tiger",
        "name": "Tiger",
        "scientificName": "Panthera tigris",
        "description": "The largest living cat species, recognized for its dark vertical stripes on reddish-orange fur.",
        "averageLifespan": 15,
        "imageUrl": "https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_panthera_tigris", "name": "Bengal / Siberian Tiger", "scientificName": "Panthera tigris"},
        "class": "Mammal",
        "habitats": ["Forest", "Wetland"],
        "diet": "Carnivore",
        "foods": ["Deer", "Wild Boar"],
        "status": "Endangered",
        "continents": ["Asia"]
    },
    {
        "id": "animal_lion",
        "name": "Lion",
        "scientificName": "Panthera leo",
        "description": "Apex social predator that lives in prides, celebrated as the King of the Jungle.",
        "averageLifespan": 14,
        "imageUrl": "https://images.unsplash.com/photo-1546182990-dffeafbe841d?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_panthera_leo", "name": "African Lion", "scientificName": "Panthera leo"},
        "class": "Mammal",
        "habitats": ["Savanna", "Grassland"],
        "diet": "Carnivore",
        "foods": ["Zebra", "Antelope", "Buffalo"],
        "status": "Vulnerable",
        "continents": ["Africa", "Asia"]
    },
    {
        "id": "animal_elephant",
        "name": "Elephant",
        "scientificName": "Elephas maximus",
        "description": "Earth's largest land mammal possessing immense trunks, ivory tusks, and extraordinary memory.",
        "averageLifespan": 65,
        "imageUrl": "https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_elephas_maximus", "name": "Asian Elephant", "scientificName": "Elephas maximus"},
        "class": "Mammal",
        "habitats": ["Forest", "Grassland"],
        "diet": "Herbivore",
        "foods": ["Grass", "Leaves", "Fruits", "Bark"],
        "status": "Endangered",
        "continents": ["Asia", "Africa"]
    },
    {
        "id": "animal_leopard",
        "name": "Leopard",
        "scientificName": "Panthera pardus",
        "description": "Graceful solitary predator known for rosette patterns and unmatched tree climbing capability.",
        "averageLifespan": 15,
        "imageUrl": "https://images.unsplash.com/photo-1456926631375-92c8ce872def?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_panthera_pardus", "name": "Leopard", "scientificName": "Panthera pardus"},
        "class": "Mammal",
        "habitats": ["Forest", "Savanna", "Mountain"],
        "diet": "Carnivore",
        "foods": ["Deer", "Antelope", "Monkeys"],
        "status": "Vulnerable",
        "continents": ["Africa", "Asia"]
    },
    {
        "id": "animal_cheetah",
        "name": "Cheetah",
        "scientificName": "Acinonyx jubatus",
        "description": "The fastest land animal on Earth, capable of reaching speeds up to 70 miles per hour.",
        "averageLifespan": 12,
        "imageUrl": "https://images.unsplash.com/photo-1547721064-da6cfb341d50?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_acinonyx_jubatus", "name": "Cheetah", "scientificName": "Acinonyx jubatus"},
        "class": "Mammal",
        "habitats": ["Savanna", "Grassland"],
        "diet": "Carnivore",
        "foods": ["Antelope", "Hares"],
        "status": "Vulnerable",
        "continents": ["Africa"]
    },
    {
        "id": "animal_giraffe",
        "name": "Giraffe",
        "scientificName": "Giraffa camelopardalis",
        "description": "The tallest living terrestrial animal, browsing foliage in the high treetops with its long neck.",
        "averageLifespan": 25,
        "imageUrl": "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_giraffa_camelopardalis", "name": "Northern Giraffe", "scientificName": "Giraffa camelopardalis"},
        "class": "Mammal",
        "habitats": ["Savanna", "Grassland"],
        "diet": "Herbivore",
        "foods": ["Leaves", "Twigs", "Fruits"],
        "status": "Vulnerable",
        "continents": ["Africa"]
    },
    {
        "id": "animal_zebra",
        "name": "Zebra",
        "scientificName": "Equus quagga",
        "description": "African equines famous for distinctive black-and-white striped coats that deter biting insects.",
        "averageLifespan": 20,
        "imageUrl": "https://images.unsplash.com/photo-1526095179574-86e545346ae6?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_equus_quagga", "name": "Plains Zebra", "scientificName": "Equus quagga"},
        "class": "Mammal",
        "habitats": ["Savanna", "Grassland"],
        "diet": "Herbivore",
        "foods": ["Grass", "Herbs", "Leaves"],
        "status": "Near Threatened",
        "continents": ["Africa"]
    },
    {
        "id": "animal_gorilla",
        "name": "Gorilla",
        "scientificName": "Gorilla beringei",
        "description": "Intelligent, ground-dwelling herbivorous apes inhabiting the tropical forests of equatorial Africa.",
        "averageLifespan": 40,
        "imageUrl": "https://images.unsplash.com/photo-1534759846116-5799c33ce22a?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_gorilla_beringei", "name": "Mountain Gorilla", "scientificName": "Gorilla beringei"},
        "class": "Mammal",
        "habitats": ["Forest", "Mountain"],
        "diet": "Herbivore",
        "foods": ["Leaves", "Fruits", "Stems", "Bamboo"],
        "status": "Critically Endangered",
        "continents": ["Africa"]
    },
    {
        "id": "animal_panda",
        "name": "Giant Panda",
        "scientificName": "Ailuropoda melanoleuca",
        "description": "Beloved black-and-white bear native to south-central China that eats almost exclusively bamboo.",
        "averageLifespan": 20,
        "imageUrl": "https://images.unsplash.com/photo-1527118732049-c88155f2107c?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_ailuropoda_melanoleuca", "name": "Giant Panda", "scientificName": "Ailuropoda melanoleuca"},
        "class": "Mammal",
        "habitats": ["Forest", "Mountain"],
        "diet": "Herbivore",
        "foods": ["Bamboo", "Shoots", "Grass"],
        "status": "Vulnerable",
        "continents": ["Asia"]
    },
    {
        "id": "animal_polar_bear",
        "name": "Polar Bear",
        "scientificName": "Ursus maritimus",
        "description": "Hypercarnivorous marine bear roaming the Arctic ice sheets, reliant on pack ice to hunt seals.",
        "averageLifespan": 25,
        "imageUrl": "https://images.unsplash.com/photo-1589656966895-2f33e7653819?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_ursus_maritimus", "name": "Polar Bear", "scientificName": "Ursus maritimus"},
        "class": "Mammal",
        "habitats": ["Polar Tundra", "Ocean"],
        "diet": "Carnivore",
        "foods": ["Seals", "Fish", "Whale Carcasses"],
        "status": "Vulnerable",
        "continents": ["North America", "Europe", "Asia"]
    },
    {
        "id": "animal_brown_bear",
        "name": "Brown Bear",
        "scientificName": "Ursus arctos",
        "description": "Massive adaptable omnivore inhabiting temperate forests and mountainous valleys.",
        "averageLifespan": 25,
        "imageUrl": "https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_ursus_arctos", "name": "Eurasian Brown Bear", "scientificName": "Ursus arctos"},
        "class": "Mammal",
        "habitats": ["Forest", "Mountain", "River"],
        "diet": "Omnivore",
        "foods": ["Fish", "Berries", "Roots", "Small Mammals"],
        "status": "Least Concern",
        "continents": ["Europe", "North America", "Asia"]
    },
    {
        "id": "animal_wolf",
        "name": "Wolf",
        "scientificName": "Canis lupus",
        "description": "Social apex pack canine known for complex hierarchical pack dynamics and haunting howls.",
        "averageLifespan": 13,
        "imageUrl": "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_canis_lupus", "name": "Gray Wolf", "scientificName": "Canis lupus"},
        "class": "Mammal",
        "habitats": ["Forest", "Grassland", "Mountain"],
        "diet": "Carnivore",
        "foods": ["Deer", "Moose", "Small Mammals"],
        "status": "Least Concern",
        "continents": ["North America", "Europe", "Asia"]
    },
    {
        "id": "animal_fox",
        "name": "Red Fox",
        "scientificName": "Vulpes vulpes",
        "description": "Clever and adaptable small canid with rusty-red fur, white chest, and a bushy tail.",
        "averageLifespan": 8,
        "imageUrl": "https://images.unsplash.com/photo-1474511320723-9a56873867b5?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_vulpes_vulpes", "name": "Red Fox", "scientificName": "Vulpes vulpes"},
        "class": "Mammal",
        "habitats": ["Forest", "Grassland"],
        "diet": "Omnivore",
        "foods": ["Rodents", "Berries", "Insects", "Birds"],
        "status": "Least Concern",
        "continents": ["Europe", "Asia", "North America", "Australia"]
    },
    {
        "id": "animal_deer",
        "name": "Red Deer",
        "scientificName": "Cervus elaphus",
        "description": "Majestic woodland ungulate whose stags display large branching antlers during autumn rutting.",
        "averageLifespan": 16,
        "imageUrl": "https://images.unsplash.com/photo-1484406566174-9da000fda645?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_cervus_elaphus", "name": "Red Deer", "scientificName": "Cervus elaphus"},
        "class": "Mammal",
        "habitats": ["Forest", "Grassland", "Mountain"],
        "diet": "Herbivore",
        "foods": ["Grass", "Leaves", "Bark", "Acorns"],
        "status": "Least Concern",
        "continents": ["Europe", "Asia"]
    },
    {
        "id": "animal_rhinoceros",
        "name": "Rhinoceros",
        "scientificName": "Rhinoceros unicornis",
        "description": "Armored megaherbivore equipped with formidable keratin horns, threatened by poaching.",
        "averageLifespan": 40,
        "imageUrl": "https://images.unsplash.com/photo-1575550959106-5a7defe28b56?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_rhinoceros_unicornis", "name": "Greater One-Horned Rhino", "scientificName": "Rhinoceros unicornis"},
        "class": "Mammal",
        "habitats": ["Grassland", "Wetland"],
        "diet": "Herbivore",
        "foods": ["Grass", "Leaves", "Aquatic Plants"],
        "status": "Vulnerable",
        "continents": ["Asia", "Africa"]
    },
    {
        "id": "animal_hippopotamus",
        "name": "Hippopotamus",
        "scientificName": "Hippopotamus amphibius",
        "description": "Semi-aquatic river heavyweight spending daylight immersed in water and grazing ashore at night.",
        "averageLifespan": 45,
        "imageUrl": "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_hippopotamus_amphibius", "name": "Common Hippopotamus", "scientificName": "Hippopotamus amphibius"},
        "class": "Mammal",
        "habitats": ["River", "Wetland"],
        "diet": "Herbivore",
        "foods": ["Grass", "Shoots", "Aquatic Plants"],
        "status": "Vulnerable",
        "continents": ["Africa"]
    },
    {
        "id": "animal_kangaroo",
        "name": "Red Kangaroo",
        "scientificName": "Osphranter rufus",
        "description": "Iconic Australian bipedal marsupial with powerful hind legs designed for high-speed hopping.",
        "averageLifespan": 23,
        "imageUrl": "https://images.unsplash.com/photo-1563281577-a7be47e20db9?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_osphranter_rufus", "name": "Red Kangaroo", "scientificName": "Osphranter rufus"},
        "class": "Mammal",
        "habitats": ["Grassland", "Desert"],
        "diet": "Herbivore",
        "foods": ["Grass", "Shrubs", "Herbs"],
        "status": "Least Concern",
        "continents": ["Australia"]
    },
    {
        "id": "animal_koala",
        "name": "Koala",
        "scientificName": "Phascolarctos cinereus",
        "description": "Tree-dwelling marsupial native to eastern Australia, subsisting almost entirely on eucalyptus leaves.",
        "averageLifespan": 15,
        "imageUrl": "https://images.unsplash.com/photo-1526716173434-a1b560f2065d?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_phascolarctos_cinereus", "name": "Koala", "scientificName": "Phascolarctos cinereus"},
        "class": "Mammal",
        "habitats": ["Forest"],
        "diet": "Herbivore",
        "foods": ["Leaves", "Eucalyptus"],
        "status": "Endangered",
        "continents": ["Australia"]
    },
    {
        "id": "animal_dolphin",
        "name": "Bottlenose Dolphin",
        "scientificName": "Tursiops truncatus",
        "description": "Highly intelligent marine mammal utilizing echolocation for navigation and cooperative hunting.",
        "averageLifespan": 40,
        "imageUrl": "https://images.unsplash.com/photo-1570481662006-a3a1374699e8?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_tursiops_truncatus", "name": "Common Bottlenose Dolphin", "scientificName": "Tursiops truncatus"},
        "class": "Mammal",
        "habitats": ["Ocean"],
        "diet": "Carnivore",
        "foods": ["Fish", "Squid", "Crustaceans"],
        "status": "Least Concern",
        "continents": ["Asia", "Europe", "North America", "South America", "Australia", "Africa"]
    },
    {
        "id": "animal_whale",
        "name": "Blue Whale",
        "scientificName": "Balaenoptera musculus",
        "description": "The largest creature ever known to have lived on Earth, filtering tons of krill through baleen plates.",
        "averageLifespan": 85,
        "imageUrl": "https://images.unsplash.com/photo-1568430462989-44163eb1752f?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_balaenoptera_musculus", "name": "Blue Whale", "scientificName": "Balaenoptera musculus"},
        "class": "Mammal",
        "habitats": ["Ocean"],
        "diet": "Carnivore",
        "foods": ["Krill", "Plankton"],
        "status": "Endangered",
        "continents": ["Antarctica", "North America", "Asia", "Europe", "Australia"]
    },
    # BIRDS
    {
        "id": "animal_eagle",
        "name": "Bald Eagle",
        "scientificName": "Haliaeetus leucocephalus",
        "description": "Fierce bird of prey with keen eyesight, white feathered head, and razor-sharp talons.",
        "averageLifespan": 20,
        "imageUrl": "https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_haliaeetus_leucocephalus", "name": "Bald Eagle", "scientificName": "Haliaeetus leucocephalus"},
        "class": "Bird",
        "habitats": ["Forest", "River", "Wetland"],
        "diet": "Carnivore",
        "foods": ["Fish", "Small Mammals", "Carrion"],
        "status": "Least Concern",
        "continents": ["North America"]
    },
    {
        "id": "animal_parrot",
        "name": "Scarlet Macaw",
        "scientificName": "Ara macao",
        "description": "Brilliantly colored neotropical parrot with bright red, yellow, and blue plumage.",
        "averageLifespan": 50,
        "imageUrl": "https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_ara_macao", "name": "Scarlet Macaw", "scientificName": "Ara macao"},
        "class": "Bird",
        "habitats": ["Forest"],
        "diet": "Herbivore",
        "foods": ["Fruits", "Seeds", "Nuts"],
        "status": "Least Concern",
        "continents": ["South America", "North America"]
    },
    {
        "id": "animal_penguin",
        "name": "Emperor Penguin",
        "scientificName": "Aptenodytes forsteri",
        "description": "Tallest and heaviest of all living penguin species, enduring brutal Antarctic winters.",
        "averageLifespan": 20,
        "imageUrl": "https://images.unsplash.com/photo-1598439210625-5067c578f3f6?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_aptenodytes_forsteri", "name": "Emperor Penguin", "scientificName": "Aptenodytes forsteri"},
        "class": "Bird",
        "habitats": ["Polar Tundra", "Ocean"],
        "diet": "Carnivore",
        "foods": ["Fish", "Krill", "Squid"],
        "status": "Near Threatened",
        "continents": ["Antarctica"]
    },
    {
        "id": "animal_owl",
        "name": "Great Horned Owl",
        "scientificName": "Bubo virginianus",
        "description": "Nocturnal raptor capable of silent flight, equipped with large yellow eyes and feather tufts.",
        "averageLifespan": 15,
        "imageUrl": "https://images.unsplash.com/photo-1579273166152-d725a4e2b755?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_bubo_virginianus", "name": "Great Horned Owl", "scientificName": "Bubo virginianus"},
        "class": "Bird",
        "habitats": ["Forest", "Grassland", "Mountain"],
        "diet": "Carnivore",
        "foods": ["Rodents", "Small Mammals", "Insects"],
        "status": "Least Concern",
        "continents": ["North America", "South America"]
    },
    {
        "id": "animal_flamingo",
        "name": "Greater Flamingo",
        "scientificName": "Phoenicopterus roseus",
        "description": "Wading bird famous for pink plumage derived from carotenoid pigments in its diet.",
        "averageLifespan": 30,
        "imageUrl": "https://images.unsplash.com/photo-1497206365907-f5e630693df0?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_phoenicopterus_roseus", "name": "Greater Flamingo", "scientificName": "Phoenicopterus roseus"},
        "class": "Bird",
        "habitats": ["Wetland"],
        "diet": "Omnivore",
        "foods": ["Crustaceans", "Plankton", "Insects"],
        "status": "Least Concern",
        "continents": ["Africa", "Asia", "Europe"]
    },
    {
        "id": "animal_peacock",
        "name": "Indian Peafowl",
        "scientificName": "Pavo cristatus",
        "description": "National bird of India celebrated for iridescent blue crest and dramatic eye-spotted tail train.",
        "averageLifespan": 18,
        "imageUrl": "https://images.unsplash.com/photo-1582845512747-e42001c95638?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_pavo_cristatus", "name": "Indian Peafowl", "scientificName": "Pavo cristatus"},
        "class": "Bird",
        "habitats": ["Forest", "Grassland"],
        "diet": "Omnivore",
        "foods": ["Seeds", "Insects", "Berries", "Small Reptiles"],
        "status": "Least Concern",
        "continents": ["Asia"]
    },
    # REPTILES
    {
        "id": "animal_crocodile",
        "name": "Saltwater Crocodile",
        "scientificName": "Crocodylus porosus",
        "description": "Earth's largest living reptile, a formidable ambush predator dominating tidal rivers and mangroves.",
        "averageLifespan": 70,
        "imageUrl": "https://images.unsplash.com/photo-1520542099817-0d19524eccca?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_crocodylus_porosus", "name": "Saltwater Crocodile", "scientificName": "Crocodylus porosus"},
        "class": "Reptile",
        "habitats": ["River", "Wetland", "Ocean"],
        "diet": "Carnivore",
        "foods": ["Fish", "Deer", "Birds", "Crustaceans"],
        "status": "Least Concern",
        "continents": ["Asia", "Australia"]
    },
    {
        "id": "animal_alligator",
        "name": "American Alligator",
        "scientificName": "Alligator mississippiensis",
        "description": "Keystone reptile of southern American swamps, known for rounded broad snouts.",
        "averageLifespan": 45,
        "imageUrl": "https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_alligator_mississippiensis", "name": "American Alligator", "scientificName": "Alligator mississippiensis"},
        "class": "Reptile",
        "habitats": ["Wetland", "River"],
        "diet": "Carnivore",
        "foods": ["Fish", "Turtles", "Small Mammals", "Birds"],
        "status": "Least Concern",
        "continents": ["North America"]
    },
    {
        "id": "animal_python",
        "name": "Burmese Python",
        "scientificName": "Python bivittatus",
        "description": "Among the largest snakes on Earth, constricting prey with overwhelming muscular power.",
        "averageLifespan": 22,
        "imageUrl": "https://images.unsplash.com/photo-1531386151447-fd76ad50012f?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_python_bivittatus", "name": "Burmese Python", "scientificName": "Python bivittatus"},
        "class": "Reptile",
        "habitats": ["Forest", "Wetland"],
        "diet": "Carnivore",
        "foods": ["Rodents", "Birds", "Small Mammals"],
        "status": "Vulnerable",
        "continents": ["Asia", "North America"]
    },
    {
        "id": "animal_king_cobra",
        "name": "King Cobra",
        "scientificName": "Ophiophagus hannah",
        "description": "The world's longest venomous snake, specialized in preying predominantly upon other snakes.",
        "averageLifespan": 20,
        "imageUrl": "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_ophiophagus_hannah", "name": "King Cobra", "scientificName": "Ophiophagus hannah"},
        "class": "Reptile",
        "habitats": ["Forest", "Wetland"],
        "diet": "Carnivore",
        "foods": ["Snakes", "Lizards", "Rodents"],
        "status": "Vulnerable",
        "continents": ["Asia"]
    },
    {
        "id": "animal_sea_turtle",
        "name": "Green Sea Turtle",
        "scientificName": "Chelonia mydas",
        "description": "Ancient marine reptile undertaking cross-ocean migrations to nest on sandy beaches.",
        "averageLifespan": 75,
        "imageUrl": "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_chelonia_mydas", "name": "Green Sea Turtle", "scientificName": "Chelonia mydas"},
        "class": "Reptile",
        "habitats": ["Ocean"],
        "diet": "Herbivore",
        "foods": ["Seagrass", "Algae"],
        "status": "Endangered",
        "continents": ["Asia", "Africa", "North America", "South America", "Australia"]
    },
    # FISH
    {
        "id": "animal_shark",
        "name": "Great White Shark",
        "scientificName": "Carcharodon carcharias",
        "description": "Formidable marine apex predator possessing serrated teeth and keen electroreceptive ampullae.",
        "averageLifespan": 70,
        "imageUrl": "https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_carcharodon_carcharias", "name": "Great White Shark", "scientificName": "Carcharodon carcharias"},
        "class": "Fish",
        "habitats": ["Ocean"],
        "diet": "Carnivore",
        "foods": ["Fish", "Seals", "Squid"],
        "status": "Vulnerable",
        "continents": ["North America", "Africa", "Australia", "Europe", "Asia"]
    },
    {
        "id": "animal_salmon",
        "name": "Atlantic Salmon",
        "scientificName": "Salmo salar",
        "description": "Anadromous fish famous for swimming upstream against fierce currents to spawn in native rivers.",
        "averageLifespan": 8,
        "imageUrl": "https://images.unsplash.com/photo-1534043464124-3be32fe000c9?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_salmo_salar", "name": "Atlantic Salmon", "scientificName": "Salmo salar"},
        "class": "Fish",
        "habitats": ["River", "Ocean"],
        "diet": "Carnivore",
        "foods": ["Insects", "Small Crustaceans", "Fish"],
        "status": "Near Threatened",
        "continents": ["Europe", "North America"]
    },
    {
        "id": "animal_clownfish",
        "name": "Clownfish",
        "scientificName": "Amphiprion ocellaris",
        "description": "Vibrant orange reef fish that shares a famous mutualistic symbiosis with stinging sea anemones.",
        "averageLifespan": 10,
        "imageUrl": "https://images.unsplash.com/photo-1524704654690-b56c05c78a00?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_amphiprion_ocellaris", "name": "Ocellaris Clownfish", "scientificName": "Amphiprion ocellaris"},
        "class": "Fish",
        "habitats": ["Ocean"],
        "diet": "Omnivore",
        "foods": ["Algae", "Plankton", "Crustaceans"],
        "status": "Least Concern",
        "continents": ["Asia", "Australia"]
    },
    # AMPHIBIANS
    {
        "id": "animal_frog",
        "name": "Red-Eyed Tree Frog",
        "scientificName": "Agalychnis callidryas",
        "description": "Rainforest arboreal frog possessing vivid scarlet eyes and bright neon green coloration.",
        "averageLifespan": 5,
        "imageUrl": "https://images.unsplash.com/photo-1559253664-ca249d4608c6?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_agalychnis_callidryas", "name": "Red-Eyed Tree Frog", "scientificName": "Agalychnis callidryas"},
        "class": "Amphibian",
        "habitats": ["Forest", "Wetland"],
        "diet": "Insectivore",
        "foods": ["Insects", "Crickets", "Moths", "Flies"],
        "status": "Least Concern",
        "continents": ["North America", "South America"]
    },
    {
        "id": "animal_poison_dart_frog",
        "name": "Golden Poison Frog",
        "scientificName": "Phyllobates terribilis",
        "description": "Among the most toxic animals on Earth, its skin toxins can incapacitate predators within minutes.",
        "averageLifespan": 7,
        "imageUrl": "https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_phyllobates_terribilis", "name": "Golden Poison Frog", "scientificName": "Phyllobates terribilis"},
        "class": "Amphibian",
        "habitats": ["Forest"],
        "diet": "Insectivore",
        "foods": ["Ants", "Termites", "Beetles"],
        "status": "Endangered",
        "continents": ["South America"]
    },
    # INVERTEBRATES & INSECTS
    {
        "id": "animal_octopus",
        "name": "Common Octopus",
        "scientificName": "Octopus vulgaris",
        "description": "Master of camouflage and puzzle-solving possessing three hearts, blue blood, and eight supple arms.",
        "averageLifespan": 2,
        "imageUrl": "https://images.unsplash.com/photo-1545671913-b89ac1b4ac10?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_octopus_vulgaris", "name": "Common Octopus", "scientificName": "Octopus vulgaris"},
        "class": "Fish",  # Cataloged under aquatic biology / Marine
        "habitats": ["Ocean"],
        "diet": "Carnivore",
        "foods": ["Crabs", "Clams", "Fish"],
        "status": "Least Concern",
        "continents": ["Europe", "Africa", "Asia", "North America"]
    },
    {
        "id": "animal_butterfly",
        "name": "Monarch Butterfly",
        "scientificName": "Danaus plexippus",
        "description": "Famed migratory insect completing multi-generational transcontinental journeys across North America.",
        "averageLifespan": 1,
        "imageUrl": "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_danaus_plexippus", "name": "Monarch Butterfly", "scientificName": "Danaus plexippus"},
        "class": "Insect",
        "habitats": ["Forest", "Grassland"],
        "diet": "Herbivore",
        "foods": ["Nectar", "Milkweed"],
        "status": "Endangered",
        "continents": ["North America", "South America", "Australia"]
    },
    {
        "id": "animal_honey_bee",
        "name": "Western Honey Bee",
        "scientificName": "Apis mellifera",
        "description": "Essential pollinator organizing complex social colonies that produce beeswax and honey.",
        "averageLifespan": 1,
        "imageUrl": "https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80",
        "species": {"id": "species_apis_mellifera", "name": "Western Honey Bee", "scientificName": "Apis mellifera"},
        "class": "Insect",
        "habitats": ["Grassland", "Forest"],
        "diet": "Herbivore",
        "foods": ["Nectar", "Pollen"],
        "status": "Least Concern",
        "continents": ["Europe", "Africa", "Asia", "North America", "South America", "Australia"]
    }
]
